import type { ImageSourcePropType } from 'react-native';

export const COURSE_IMAGES: Record<string, ImageSourcePropType> = {
  'intersection.svg': require('../../assets/course/intersection.svg.png'),
  'route-automobile-autoroute.svg': require('../../assets/course/route-automobile-autoroute.svg.png'),
  'route-chaussees-voies.svg': require('../../assets/course/route-chaussees-voies.svg.png'),
  'familles-panneaux.svg': require('../../assets/course/familles-panneaux.svg.png'),
  'balises.svg': require('../../assets/course/balises.svg.png'),
  'vehicules-prioritaires.svg': require('../../assets/course/vehicules-prioritaires.svg.png'),
  'categories-permis.svg': require('../../assets/course/categories-permis.svg.png'),
  'planche-53.webp': require('../../assets/course/support/planche-53.webp'),
  'planche-54.webp': require('../../assets/course/support/planche-54.webp'),
  'planche-55.webp': require('../../assets/course/support/planche-55.webp'),
  'planche-56.webp': require('../../assets/course/support/planche-56.webp'),
  'planche-57.webp': require('../../assets/course/support/planche-57.webp'),
  'planche-58.webp': require('../../assets/course/support/planche-58.webp'),
  'planche-59.webp': require('../../assets/course/support/planche-59.webp'),
  'planche-60.webp': require('../../assets/course/support/planche-60.webp'),
  'planche-61.webp': require('../../assets/course/support/planche-61.webp'),
  'planche-62.webp': require('../../assets/course/support/planche-62.webp'),
  'planche-63.webp': require('../../assets/course/support/planche-63.webp'),
  'planche-64.webp': require('../../assets/course/support/planche-64.webp'),
  'planche-65.webp': require('../../assets/course/support/planche-65.webp'),
  'planche-66.webp': require('../../assets/course/support/planche-66.webp'),
  'planche-67.webp': require('../../assets/course/support/planche-67.webp'),
  'planche-68.webp': require('../../assets/course/support/planche-68.webp'),
  'planche-69.webp': require('../../assets/course/support/planche-69.webp'),
  'planche-70.webp': require('../../assets/course/support/planche-70.webp'),
  'planche-71.webp': require('../../assets/course/support/planche-71.webp'),
  'planche-72.webp': require('../../assets/course/support/planche-72.webp'),
  'planche-73.webp': require('../../assets/course/support/planche-73.webp'),
  'planche-74.webp': require('../../assets/course/support/planche-74.webp'),
  'planche-75.webp': require('../../assets/course/support/planche-75.webp'),
  'planche-76.webp': require('../../assets/course/support/planche-76.webp'),
  'planche-77.webp': require('../../assets/course/support/planche-77.webp'),
  'planche-78.webp': require('../../assets/course/support/planche-78.webp'),
  'planche-79.webp': require('../../assets/course/support/planche-79.webp'),
  'planche-80.webp': require('../../assets/course/support/planche-80.webp'),
  'circuit-examen-benin.webp': require('../../assets/course/support/circuit-examen-benin.webp'),
};

const SUPPORT_PAGE_RATIO = 1191 / 862;

export const COURSE_IMAGE_RATIOS: Record<string, number> = {
  'intersection.svg': 1000 / 656,
  'route-automobile-autoroute.svg': 932 / 468,
  'route-chaussees-voies.svg': 884 / 448,
  'familles-panneaux.svg': 944 / 372,
  'balises.svg': 714 / 364,
  'vehicules-prioritaires.svg': 882 / 388,
  'categories-permis.svg': 944 / 456,
  ...Object.fromEntries(Array.from({ length: 28 }, (_, index) => [`planche-${index + 53}.webp`, SUPPORT_PAGE_RATIO])),
  'circuit-examen-benin.webp': 862 / 1191,
};
