import type { ImageSourcePropType } from 'react-native';
import { Asset } from 'expo-asset';

export const COURSE_IMAGES: Record<string, ImageSourcePropType> = {
  'intersection.svg': require('../../assets/course/intersection.svg.png'),
  'route-automobile-autoroute.svg': require('../../assets/course/route-automobile-autoroute.svg.png'),
  'route-chaussees-voies.svg': require('../../assets/course/route-chaussees-voies.svg.png'),
  'familles-panneaux.svg': require('../../assets/course/familles-panneaux.svg.png'),
  'balises.svg': require('../../assets/course/balises.svg.png'),
  'vehicules-prioritaires.svg': require('../../assets/course/vehicules-prioritaires.svg.png'),
  'categories-permis.svg': require('../../assets/course/categories-permis.svg.png'),
  'vertical-danger.png': require('../../assets/course/course-2/vertical-danger.png'),
  'vertical-interdiction.png': require('../../assets/course/course-2/vertical-interdiction.png'),
  'vertical-fin-interdiction.png': require('../../assets/course/course-2/vertical-fin-interdiction.png'),
  'vertical-obligation.png': require('../../assets/course/course-2/vertical-obligation.png'),
  'vertical-fin-obligation.png': require('../../assets/course/course-2/vertical-fin-obligation.png'),
  'vertical-indication.png': require('../../assets/course/course-2/vertical-indication.png'),
  'vertical-priorite.png': require('../../assets/course/course-2/vertical-priorite.png'),
  'marquage-lignes.png': require('../../assets/course/course-2/marquage-lignes.png'),
  'marquage-fleches.png': require('../../assets/course/course-2/marquage-fleches.png'),
  'marquage-zones.png': require('../../assets/course/course-2/marquage-zones.png'),
  'marquage-stockage.png': require('../../assets/course/course-2/marquage-stockage.png'),
  'feux-circulation.png': require('../../assets/course/course-2/feux-circulation.png'),
  'agents-positions.png': require('../../assets/course/course-2/agents-positions.png'),
  'balises-course-2.png': require('../../assets/course/course-2/balises.png'),
  'recap-verticale.png': require('../../assets/course/course-2/recap-verticale.png'),
  'recap-marquage.png': require('../../assets/course/course-2/recap-marquage.png'),
  'recap-agents.png': require('../../assets/course/course-2/recap-agents.png'),
  'panneaux-danger-frequents.webp': require('../../assets/course/course-2/panneaux-danger-frequents.webp'),
  'panneaux-indication-frequents.webp': require('../../assets/course/course-2/panneaux-indication-frequents.webp'),
  'panneaux-interdiction-frequents.webp': require('../../assets/course/course-2/panneaux-interdiction-frequents.webp'),
  'panneaux-obligation-frequents.webp': require('../../assets/course/course-2/panneaux-obligation-frequents.webp'),
  'recap-reconnaissance-panneaux.webp': require('../../assets/course/course-2/recap-reconnaissance-panneaux.webp'),
  'autoroute-circulation.png': require('../../assets/course/course-3/autoroute-circulation.png'),
  'autoroute-urgence.png': require('../../assets/course/course-3/autoroute-urgence.png'),
  'priorite-droite.png': require('../../assets/course/course-3/priorite-droite.png'),
  'perte-priorite-sortie.png': require('../../assets/course/course-3/perte-priorite-sortie.png'),
  'recap-autoroute.png': require('../../assets/course/course-3/recap-autoroute.png'),
  'recap-priorites.png': require('../../assets/course/course-3/recap-priorites.png'),
  'intersection-complexe.png': require('../../assets/course/course-3/intersection-complexe.png'),
  'planche-53.webp': require('../../assets/course/support/planche-53.webp'),
  'planche-54.webp': require('../../assets/course/support/planche-54.webp'),
  'planche-55.webp': require('../../assets/course/support/planche-55.webp'),
  'planche-56.webp': require('../../assets/course/support/planche-56.webp'),
  'planche-57.webp': require('../../assets/course/support/planche-57.webp'),
  'planche-58.webp': require('../../assets/course/support/planche-58.webp'),
  'planche-59.webp': require('../../assets/course/support/planche-59.webp'),
  'planche-60.webp': require('../../assets/course/support/planche-60.webp'),
  'planche-61.webp': require('../../assets/course/support/planche-61.webp'),
  'planche-62.webp': require('../../assets/course/support/planche-62.webp'),
  'planche-63.webp': require('../../assets/course/support/planche-63.webp'),
  'planche-64.webp': require('../../assets/course/support/planche-64.webp'),
  'planche-65.webp': require('../../assets/course/support/planche-65.webp'),
  'planche-66.webp': require('../../assets/course/support/planche-66.webp'),
  'planche-67.webp': require('../../assets/course/support/planche-67.webp'),
  'planche-68.webp': require('../../assets/course/support/planche-68.webp'),
  'planche-69.webp': require('../../assets/course/support/planche-69.webp'),
  'planche-70.webp': require('../../assets/course/support/planche-70.webp'),
  'planche-71.webp': require('../../assets/course/support/planche-71.webp'),
  'planche-72.webp': require('../../assets/course/support/planche-72.webp'),
  'planche-73.webp': require('../../assets/course/support/planche-73.webp'),
  'planche-74.webp': require('../../assets/course/support/planche-74.webp'),
  'planche-75.webp': require('../../assets/course/support/planche-75.webp'),
  'planche-76.webp': require('../../assets/course/support/planche-76.webp'),
  'planche-77.webp': require('../../assets/course/support/planche-77.webp'),
  'planche-78.webp': require('../../assets/course/support/planche-78.webp'),
  'planche-79.webp': require('../../assets/course/support/planche-79.webp'),
  'planche-80.webp': require('../../assets/course/support/planche-80.webp'),
  'circuit-examen-benin.webp': require('../../assets/course/support/circuit-examen-benin.webp'),
};

export function getCourseImageSize(source: ImageSourcePropType) {
  const asset = Asset.fromModule(source as number);
  return { width: asset.width || 1, height: asset.height || 1 };
}

export function getCourseImageUri(source: ImageSourcePropType) {
  return Asset.fromModule(source as number).uri;
}
