import { useEffect, useState } from 'react';
import { Alert, Pressable, View } from 'react-native';
import { AppText as Text } from '@/src/components/app-text';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { Card, EmptyState, Heading, Loading, Screen } from '@/src/components/ui';
import { getCourse, getCourseSubjectQuestions, getCourseSubjects } from '@/src/db/queries';
import { useQuiz } from '@/src/features/quiz-context';
import { useThemePreferences } from '@/src/theme/preferences';
import type { Course, Subject } from '@/src/types/models';
import { colors } from '@/src/theme/colors';

export default function CourseSubjects(){const{id}=useLocalSearchParams<{id:string}>();const courseId=Number(id);const db=useSQLiteContext();const router=useRouter();const quiz=useQuiz();const{selectedPermitTypes}=useThemePreferences();const[course,setCourse]=useState<Course|null>();const[subjects,setSubjects]=useState<Subject[]|null>(null);useEffect(()=>{Promise.all([getCourse(db,courseId),getCourseSubjects(db,courseId)]).then(([nextCourse,nextSubjects])=>{setCourse(nextCourse);setSubjects(nextSubjects)})},[db,courseId]);if(subjects===null)return <Loading/>;const start=async(subject:Subject)=>{const questions=await getCourseSubjectQuestions(db,subject.id,selectedPermitTypes);if(!questions.length)return Alert.alert('Sujet vide','Aucune question ne correspond aux types de permis sélectionnés.');quiz.start({mode:'subject',categoryId:null,categoryName:course?.title??'Cours',subjectIndex:subject.number,subjectId:subject.id,questions,answers:{},startedAt:Date.now()});router.push('/quiz')};return <Screen><Heading eyebrow={`${subjects.length} sujet${subjects.length>1?'s':''}`} title={course?.title??'Sujets du cours'} subtitle="Chaque sujet utilise uniquement les types de permis sélectionnés dans vos réglages."/>{subjects.length?subjects.map(subject=><Pressable key={subject.id} onPress={()=>start(subject)} className="mb-3 active:opacity-80"><Card className="flex-row items-center"><View className="mr-4 h-12 w-12 items-center justify-center rounded-2xl bg-primarySoft"><Text className="text-lg font-black text-primary">{subject.number}</Text></View><View className="flex-1"><Text className="text-lg font-black text-ink">{subject.title}</Text><Text className="mt-1 text-sm leading-5 text-inkMuted">{subject.description||`${subject.question_count} questions`}</Text><Text className="mt-1 text-xs font-bold text-primary">Jusqu’à {subject.question_count} questions</Text></View><Ionicons name="play-circle" size={34} color={colors.primary}/></Card></Pressable>):<EmptyState title="Aucun sujet" message="Les sujets de ce chapitre ne sont pas encore disponibles."/>}</Screen>}
